/**
 * AUTO-GENERATED by scripts/generate-format-pane-spec.mjs
 * Format Pane coverage — iterates every non-filter property from
 * e2e/fixtures/capabilities-matrix.json, feeds representative values
 * through window.__mountVisual, and asserts the visual re-renders
 * without throwing. Results are written to e2e/format-pane-results.json.
 */
import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

const PREVIEW_HTML = "visual-harness.html";
const FIXTURE_FILE = "budget-comparison.json";

const matrix = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, "fixtures/capabilities-matrix.json"), "utf-8")
);
const fixture = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, `fixtures/${FIXTURE_FILE}`), "utf-8")
);
const previewUrl = "file:///" + path.resolve(__dirname, PREVIEW_HTML).replace(/\\/g, "/");

type PropMeta = {
    objectName: string;
    propertyName: string;
    type: string;
    isFilter?: boolean;
    enumValues?: Array<{ value: string | number | boolean; displayName?: string }>;
};

function representativeValues(prop: PropMeta): Array<string | number | boolean> {
    switch (prop.type) {
        case "bool":        return [true, false];
        case "text":        return ["", "Sample"];
        case "numeric":     return [0, 12, -1];
        case "integer":     return [0, 5, 100];
        case "color":       return ["#000000", "#ff0000"];
        case "enumeration": return (prop.enumValues || []).map(e => e.value);
        default:            return [];
    }
}

type Result = {
    objectName: string;
    propertyName: string;
    type: string;
    value: unknown;
    status: "pass" | "fail";
    error?: string;
};
const results: Result[] = [];

const props: PropMeta[] = (matrix.properties || []).filter((p: PropMeta) => !p.isFilter);

test.describe.parallel("Format Pane — Auto-generated Coverage", () => {
    test.setTimeout(60_000);

    for (const prop of props) {
        const values = representativeValues(prop);
        for (const value of values) {
            const title = `${prop.objectName}.${prop.propertyName} (${prop.type}) = ${JSON.stringify(value)}`;
            test(title, async ({ page }) => {
                const pageErrors: string[] = [];
                page.on("pageerror", e => pageErrors.push(String(e.message ?? e)));
                const consoleErrors: string[] = [];
                page.on("console", msg => { if (msg.type() === "error") consoleErrors.push(msg.text()); });

                await page.goto(previewUrl, { waitUntil: "domcontentloaded" });
                await page.waitForFunction(
                    () => !!(window as any).__mountVisual && document.body.getAttribute("data-rendered") === "true",
                    undefined,
                    { timeout: 10_000 }
                );

                const containerId = `autogen-${prop.objectName}-${prop.propertyName}-${Math.random().toString(36).slice(2, 8)}`;
                const settings = { [prop.objectName]: { [prop.propertyName]: value } };

                const outcome = await page.evaluate(
                    (args: { containerId: string; fixture: unknown; settings: Record<string, unknown>; width: number; height: number }) => {
                        const div = document.createElement("div");
                        div.id = args.containerId;
                        document.body.appendChild(div);
                        try {
                            const handle = (window as any).__mountVisual({
                                containerId: args.containerId,
                                dataView: args.fixture,
                                settings: args.settings,
                                dimensions: { width: args.width, height: args.height }
                            });
                            if (handle && typeof handle.update === "function") {
                                handle.update({ settings: args.settings });
                            }
                            const c = document.getElementById(args.containerId);
                            return {
                                ok: true,
                                childCount: c ? c.childElementCount : 0,
                                hasDataRendered: document.body.getAttribute("data-rendered") === "true"
                            };
                        } catch (e: any) {
                            return { ok: false, error: String(e?.message ?? e) };
                        }
                    },
                    { containerId, fixture, settings, width: 700, height: 320 }
                );

                const record = (status: "pass" | "fail", error?: string) => {
                    results.push({
                        objectName: prop.objectName,
                        propertyName: prop.propertyName,
                        type: prop.type,
                        value,
                        status,
                        error
                    });
                };

                try {
                    if (!outcome.ok) throw new Error("mountVisual threw: " + (outcome as { error?: string }).error);
                    expect(outcome.childCount, "container should have child nodes after render").toBeGreaterThan(0);
                    expect(outcome.hasDataRendered, "data-rendered attribute should be present").toBe(true);
                    expect(pageErrors, "no uncaught page errors").toEqual([]);
                    record("pass");
                } catch (err: any) {
                    record("fail", err?.message ?? String(err));
                    throw err;
                }
            });
        }
    }

    test.afterAll(async ({}, testInfo) => {
        try {
            const wIdx = testInfo.workerIndex ?? 0;
            const out = path.resolve(__dirname, `format-pane-results.w${wIdx}.json`);
            fs.writeFileSync(out, JSON.stringify({
                workerIndex: wIdx,
                fixture: FIXTURE_FILE,
                results
            }, null, 2));
        } catch {
            /* best-effort write */
        }
    });
});
